# Generated by Django 5.0.1 on 2024-01-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
