# Generated by Django 5.0.1 on 2024-01-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clients_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, max_length=5),
        ),
    ]
