# Generated by Django 5.0.1 on 2024-01-07 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_clients_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5, message='Rating must be less than or equal to 5.'), django.core.validators.MinValueValidator(0, message='Rating must be greater than or equal to 0.')]),
        ),
    ]
