# Generated by Django 5.0 on 2024-01-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_clients_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='title',
            field=models.CharField(default='Title', max_length=255),
        ),
    ]
